laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
  'namespace' => 'Site'
], function(){

  Route::get('/', ['as' => 'home', 'uses' => 'Home\HomeController@getIndex']);
  Route::get('participe', ['as' => 'participe', 'uses' => 'Participe\ParticipeController@getIndex']);
  Route::post('participar', ['as' => 'participar', 'uses' => 'Participe\ParticipeController@postParticipar']);
  Route::get('regulamento', ['as' => 'regulamento', 'uses' => 'Regulamento\RegulamentoController@getIndex']);
  Route::get('produtos', ['as' => 'produtos', 'uses' => 'Produtos\ProdutosController@getIndex']);
  Route::get('premio', ['as' => 'premio', 'uses' => 'Premios\PremiosController@getIndex']);
  Route::get('receitas', ['as' => 'receitas', 'uses' => 'Receitas\ReceitasController@getIndex']);
  Route::get('receitas/{slug}', ['as' => 'receitas.detalhes', 'uses' => 'Receitas\ReceitasController@getDetalhes']);


});


// Authentication routes
Route::get('painel/auth/login', ['as' => 'painel.login','uses' => 'Painel\Auth\AuthController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth','uses' => 'Painel\Auth\AuthController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout','uses' => 'Painel\Auth\AuthController@getLogout']);

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function() {

  Route::get('/', ['as' => 'painel.dashboard', 'uses' => function() {
    return view('painel.dashboard.index');
  }]);

  Route::post('gravar-ordem-registros', function(Illuminate\Http\Request $request){
    $itens = $request->input('data');
    $tabela = $request->input('tabela');
    for ($i = 0; $i < count($itens); $i++)
	    DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
  });

  Route::resource('usuarios', 'Usuarios\UsuariosController');
  Route::resource('receitas', 'Receitas\ReceitasController', ['except' => ['show']]);
  Route::get('inscricoes', ['as' => 'painel.inscricoes.index', 'uses' => 'Inscricoes\InscricoesController@getIndex']);
  Route::get('inscricoes/detalhes/{id}', ['as' => 'painel.inscricoes.show', 'uses' => 'Inscricoes\InscricoesController@getDetalhes']);
  Route::post('inscricoes/remover/{id}', ['as' => 'painel.inscricoes.destroy', 'uses' => 'Inscricoes\InscricoesController@postDestroy']);
  Route::get('download-inscricoes', ['as' => 'painel.inscricoes.download', 'uses' => 'Inscricoes\InscricoesController@getDownload']);


});

laravel/app/Models/Cupom.php
<?php

namespace ItaliaGastronomica\Models;

use Illuminate\Database\Eloquent\Model;

class Cupom extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'cupons';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
    'participacoes_id',
    'codigo_1',
    'codigo_2',
    'codigo_3'
  ];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['id'];

	public function getHashAttribute()
	{
			return str_pad($this->id, 8, '0', STR_PAD_LEFT);
	}

	public function participacao()
  {
    return $this->belongsTo('ItaliaGastronomica\Models\Participacao', 'participacoes_id');
  }
}

laravel/app/Http/Controllers/Painel/Inscricoes/InscricoesController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Inscricoes;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;

use ItaliaGastronomica\Models\Participacao;

class InscricoesController extends Controller{

	public function getIndex()
	{
		$registros = Participacao::all();

		return view('painel.inscricoes.index')->with(compact('registros'));
	}

  public function getDetalhes($participacao_id){
    $registro = Participacao::find($participacao_id);
    return view('painel.inscricoes.show')->with(compact('registro'));
  }

	public function postDestroy(Request $request, $id){
		$object = Participacao::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Participação removida com sucesso.');

		return redirect()->route('painel.inscricoes.index');
	}

  public function getDownload(Request $request){
    $registros = Participacao::orderBy('cpf')->get();

    $filename = 'Cadastros_Promocao_Italia_Gastronomica_'.date('d_m_Y');

    $registrosArray = [];
		$linha = 0;		

    foreach ($registros as $key => $value) {
			if(count($value->cupons) > 0){
				foreach ($value->cupons as $cupom_index => $cupom) {
		      $registrosArray[$linha]['nome'] = $value->nome;
		      $registrosArray[$linha]['email'] = $value->email;
		      $registrosArray[$linha]['data de cadastro'] = $value->created_at->format('d/m/Y H:i');
		      $registrosArray[$linha]['cpf'] = $value->cpf;
		      $registrosArray[$linha]['cep'] = $value->cep;
		      $registrosArray[$linha]['endereco'] = $value->endereco;
		      $registrosArray[$linha]['numero'] = $value->numero;
		      $registrosArray[$linha]['complemento'] = $value->complemento;
		      $registrosArray[$linha]['bairro'] = $value->bairro;
		      $registrosArray[$linha]['cidade'] = $value->cidade;
		      $registrosArray[$linha]['estado'] = $value->estado;
		      $registrosArray[$linha]['telefone'] = $value->telefone;
		      $registrosArray[$linha]['data_nascimento'] = $value->data_nascimento->format('d/m/Y H:i');
		      $registrosArray[$linha]['sexo'] = $value->sexo;
		      $registrosArray[$linha]['estabelecimento'] = $value->estabelecimento;
		      $registrosArray[$linha]['cupom_fiscal'] = $value->cupom_fiscal;
		      $registrosArray[$linha]['codigo_1'] = $cupom->codigo_1;
		      $registrosArray[$linha]['codigo_2'] = $cupom->codigo_2;
		      $registrosArray[$linha]['codigo_3'] = $cupom->codigo_3;
					$linha++;
				}
			}
    }

    \Excel::create($filename, function($excel) use($registrosArray) {
	    $excel->sheet('Relatório de Cadastros', function($sheet) use ($registrosArray) {
	      $sheet->fromArray($registrosArray);
	    });
		})->download('xls');
  }

}

laravel/app/Http/Controllers/Painel/Receitas/ReceitasController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Receitas;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;
use ItaliaGastronomica\Libs\Thumbs;

use ItaliaGastronomica\Models\Receita;

class ReceitasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Receita::ordenado()->get();

      return view('painel.receitas.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.receitas.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'titulo' => 'required|unique:receitas,titulo',
        'imagem' => 'required|image'
    	]);

      $object = new Receita;

      $object->titulo = $request->titulo;
      $object->slug = str_slug($request->titulo);
      $object->ingredientes = $request->ingredientes;
      $object->preparo = $request->preparo;
      $object->tempo_preparo = $request->tempo_preparo;
      $object->rendimento = $request->rendimento;

      $imagem = Thumbs::make($request, 'imagem', 600, null, 'receitas/');
      if($imagem){
        $object->thumb = $imagem;
        Thumbs::makeFromFile('assets/img/receitas/', $imagem, 200, 200, 'assets/img/receitas/thumbs/');
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.receitas.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.receitas.edit')->with('registro', Receita::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'titulo' => 'required|unique:receitas,titulo,'.$id,
        'imagem' => 'sometimes|image'
    	]);

      $object = Receita::find($id);

      $object->titulo = $request->titulo;
      $object->slug = str_slug($request->titulo);
      $object->ingredientes = $request->ingredientes;
      $object->preparo = $request->preparo;
      $object->tempo_preparo = $request->tempo_preparo;
      $object->rendimento = $request->rendimento;

      $imagem = Thumbs::make($request, 'imagem', 200, 200, 'receitas/');
      if($imagem){
        $object->thumb = $imagem;
        Thumbs::makeFromFile('assets/img/receitas/', $imagem, 200, 200, 'assets/img/receitas/thumbs/');
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.receitas.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Receita::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.receitas.index');
    }

}

laravel/app/Http/Controllers/Painel/Usuarios/UsuariosController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Usuarios;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;
use View;
use Hash;

use ItaliaGastronomica\Models\User;

class UsuariosController extends Controller{

	public function index()
	{
		$usuarios = User::all();

		return view('painel.usuarios.index')->with(compact('usuarios'));
	}

	public function create()
	{
		return view('painel.usuarios.create');
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'nome' => 'required',
    	'login'             => 'required|unique:users,login',
    	'password'         => 'required|min:6',
    	'password_confirm' => 'required|min:6|same:password',
  	]);

		$object = new User;

		$object->nome = $request->nome;
		$object->login     = $request->login;
		$object->email    = $request->email;
		$object->password = Hash::make($request->password);

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Usuário criado com sucesso.');

			return redirect()->route('painel.usuarios.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar usuário! ('.$e->getMessage().')'));

		}
	}

	public function edit($id)
	{
		$usuario = User::find($id);

		return view('painel.usuarios.edit')->with(compact('usuario'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'nome' => 'required',
    	'login'             => 'required|unique:users,login,'.$id,
    	'password'         => 'min:6',
    	'password_confirm' => 'required_with:password|min:6|same:password',
  	]);

		$object = User::find($id);

		$object->nome = $request->nome;
		$object->email = $request->email;
		$object->login = $request->login;

		if($request->has('password'))
			$object->password = Hash::make($request->password);

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Usuário alterado com sucesso.');

			return redirect()->route('painel.usuarios.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar usuário! ('.$e->getMessage().')'));

		}
	}

	public function destroy(Request $request, $id)
	{
		$object = User::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Usuário removido com sucesso.');

		return redirect()->route('painel.usuarios.index');
	}
}

laravel/resources/views/painel/inscricoes/index.blade.php
@extends('painel.template')

@section('conteudo')

<div class="container-fluid padded-bottom">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <h2>Inscrições</h2>

      @include('painel.partials.mensagens')

      <hr>

      <a href="{{ url('painel/download-inscricoes') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-download"></span> Extrair Cadastros</a>

      <table class="table table-striped table-bordered table-hover ">

        <thead>
          <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>E-mail</th>
            <th>Cupons Gerados</th>
            <th><span class="glyphicon glyphicon-cog"></span></th>
          </tr>
        </thead>

        <tbody>
          @foreach ($registros as $registro)

            <tr class="tr-row">
              <td>
                {{ $registro->nome }}
              </td>
              <td>
                {{ $registro->cpf }}
              </td>
              <td>
                {{ $registro->email }}
              </td>
              <td>
                {{ count($registro->cupons) }}
              </td>
              <td class="crud-actions" style="white-space: nowrap;">
                <a href="{{ url('/painel/inscricoes/detalhes/'.$registro->id) }}" class="btn btn-primary btn-sm">visualizar</a>

                <form action="{{ URL::route('painel.inscricoes.destroy', $registro->id) }}" method="post">
                  <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                  <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>

      </table>
    </div>
  </div>
</div>

@endsection

laravel/resources/views/painel/inscricoes/show.blade.php
@extends('painel.template')

@section('conteudo')

  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">

		    <h2>
	      	Visualizar Inscrição
	      </h2>

	      <hr>

        <div class="form-group">
				  <label>Data da Inscrição</label>
					<input type="text" class="form-control" value="{{ $registro->created_at->format('d/m/Y H:i:s') }}" readonly>
				</div>

        <div class="form-group">
				  <label>Nome</label>
					<input type="text" class="form-control" value="{{ $registro->nome }}" readonly>
				</div>

        <div class="form-group">
				  <label>CPF</label>
					<input type="text" class="form-control" value="{{ $registro->cpf }}" readonly>
				</div>

        <div class="form-group">
				  <label>CEP</label>
					<input type="text" class="form-control" value="{{ $registro->cep }}" readonly>
				</div>

        <div class="form-group">
				  <label>Endereço</label>
					<input type="text" class="form-control" value="{{ $registro->endereco }}" readonly>
				</div>

        <div class="form-group">
				  <label>Número</label>
					<input type="text" class="form-control" value="{{ $registro->numero }}" readonly>
				</div>

        <div class="form-group">
				  <label>Complemento</label>
					<input type="text" class="form-control" value="{{ $registro->complemento }}" readonly>
				</div>

        <div class="form-group">
				  <label>Bairro</label>
					<input type="text" class="form-control" value="{{ $registro->bairro }}" readonly>
				</div>

        <div class="form-group">
				  <label>Cidade</label>
					<input type="text" class="form-control" value="{{ $registro->cidade }}" readonly>
				</div>

        <div class="form-group">
				  <label>Estado</label>
					<input type="text" class="form-control" value="{{ $registro->estado }}" readonly>
				</div>

        <div class="form-group">
				  <label>Telefone</label>
					<input type="text" class="form-control" value="{{ $registro->telefone }}" readonly>
				</div>

        <div class="form-group">
				  <label>E-mail</label>
					<input type="text" class="form-control" value="{{ $registro->email }}" readonly>
				</div>

        <div class="form-group">
				  <label>Data de Nascimento</label>
					<input type="text" class="form-control" value="{{ $registro->data_nascimento->format('d/m/Y') }}" readonly>
				</div>

        <div class="form-group">
				  <label>Sexo</label>
					<input type="text" class="form-control" value="{{ $registro->sexo }}" readonly>
				</div>

        <div class="form-group">
				  <label>Estabelecimento da Compra</label>
					<input type="text" class="form-control" value="{{ $registro->estabelecimento }}" readonly>
				</div>

        <div class="form-group">
				  <label>Cupom Fiscal</label>
					<input type="text" class="form-control" value="{{ $registro->cupom_fiscal }}" readonly>
				</div>

        <hr>

        <h3>Cupons</h3>

        @forelse($registro->cupons as $cupom)
          <div class="well">
            <strong>ID do Cupom:</strong> {{$cupom->hash}}<br>
            <strong>Código de Barra 1:</strong> {{$cupom->codigo_1}}<br>
            <strong>Código de Barra 2:</strong> {{$cupom->codigo_2}}<br>
            <strong>Código de Barra 3:</strong> {{$cupom->codigo_3}}
          </div>
        @empty
          <p>Nenhum cupom gerado</p>
        @endforelse

				<a href="{{ URL::route('painel.inscricoes.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</div>
  </div>

@endsection