laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group([
  'namespace' => 'Site'
], function(){

  Route::get('/', ['as' => 'home', 'uses' => 'Home\HomeController@getIndex']);
  Route::get('participe', ['as' => 'participe', 'uses' => 'Participe\ParticipeController@getIndex']);
  Route::post('participar', ['as' => 'participar', 'uses' => 'Participe\ParticipeController@postParticipar']);
  Route::get('regulamento', ['as' => 'regulamento', 'uses' => 'Regulamento\RegulamentoController@getIndex']);
  Route::get('produtos', ['as' => 'produtos', 'uses' => 'Produtos\ProdutosController@getIndex']);
  Route::get('premio', ['as' => 'premio', 'uses' => 'Premios\PremiosController@getIndex']);
  Route::get('receitas', ['as' => 'receitas', 'uses' => 'Receitas\ReceitasController@getIndex']);
  Route::get('receitas/{slug}', ['as' => 'receitas.detalhes', 'uses' => 'Receitas\ReceitasController@getDetalhes']);


});


// Authentication routes
Route::get('painel/auth/login', ['as' => 'painel.login','uses' => 'Painel\Auth\AuthController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth','uses' => 'Painel\Auth\AuthController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout','uses' => 'Painel\Auth\AuthController@getLogout']);

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function() {

  Route::get('/', ['as' => 'painel.dashboard', 'uses' => function() {
    return view('painel.dashboard.index');
  }]);

  Route::post('gravar-ordem-registros', function(Illuminate\Http\Request $request){
    $itens = $request->input('data');
    $tabela = $request->input('tabela');
    for ($i = 0; $i < count($itens); $i++)
	    DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
  });

  Route::resource('usuarios', 'Usuarios\UsuariosController');
  Route::resource('receitas', 'Receitas\ReceitasController', ['except' => ['show']]);
  Route::get('inscricoes', ['as' => 'painel.inscricoes.index', 'uses' => 'Inscricoes\InscricoesController@getIndex']);
  Route::get('inscricoes/detalhes/{id}', ['as' => 'painel.inscricoes.show', 'uses' => 'Inscricoes\InscricoesController@getDetalhes']);
  Route::post('inscricoes/remover/{id}', ['as' => 'painel.inscricoes.destroy', 'uses' => 'Inscricoes\InscricoesController@postDestroy']);
  Route::get('download-inscricoes', ['as' => 'painel.inscricoes.download', 'uses' => 'Inscricoes\InscricoesController@getDownload']);


});

laravel/app/Models/Receita.php
<?php

namespace ItaliaGastronomica\Models;

use Illuminate\Database\Eloquent\Model;

class Receita extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'receitas';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
    'titulo',
    'slug',
    'thumb',
    'ingredientes',
    'preparo',
    'tempo_preparo',
    'rendimento',
    'ordem'
  ];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['id'];

	public function scopeOrdenado($query)
	{
		return $query->orderBy('ordem', 'asc');
	}

	public function scopeFindBySlug($query, $slug)
	{
		return $query->where('slug', $slug)->firstOrFail();
	}
}

laravel/app/Http/Controllers/Painel/Inscricoes/InscricoesController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Inscricoes;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;

use ItaliaGastronomica\Models\Participacao;

class InscricoesController extends Controller{

	public function getIndex()
	{
		$registros = Participacao::all();

		return view('painel.inscricoes.index')->with(compact('registros'));
	}

  public function getDetalhes($participacao_id){
    $registro = Participacao::find($participacao_id);
    return view('painel.inscricoes.show')->with(compact('registro'));
  }

	public function postDestroy(Request $request, $id){
		$object = Participacao::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Participação removida com sucesso.');

		return redirect()->route('painel.inscricoes.index');
	}

  public function getDownload(Request $request){
    $registros = Participacao::orderBy('cpf')->get();

    $filename = 'Cadastros_Promocao_Italia_Gastronomica_'.date('d_m_Y');

    $registrosArray = [];
		$linha = 0;		

    foreach ($registros as $key => $value) {
			if(count($value->cupons) > 0){
				foreach ($value->cupons as $cupom_index => $cupom) {
		      $registrosArray[$linha]['nome'] = $value->nome;
		      $registrosArray[$linha]['email'] = $value->email;
		      $registrosArray[$linha]['data de cadastro'] = $value->created_at->format('d/m/Y H:i');
		      $registrosArray[$linha]['cpf'] = $value->cpf;
		      $registrosArray[$linha]['cep'] = $value->cep;
		      $registrosArray[$linha]['endereco'] = $value->endereco;
		      $registrosArray[$linha]['numero'] = $value->numero;
		      $registrosArray[$linha]['complemento'] = $value->complemento;
		      $registrosArray[$linha]['bairro'] = $value->bairro;
		      $registrosArray[$linha]['cidade'] = $value->cidade;
		      $registrosArray[$linha]['estado'] = $value->estado;
		      $registrosArray[$linha]['telefone'] = $value->telefone;
		      $registrosArray[$linha]['data_nascimento'] = $value->data_nascimento->format('d/m/Y H:i');
		      $registrosArray[$linha]['sexo'] = $value->sexo;
		      $registrosArray[$linha]['estabelecimento'] = $value->estabelecimento;
		      $registrosArray[$linha]['cupom_fiscal'] = $value->cupom_fiscal;
		      $registrosArray[$linha]['codigo_1'] = $cupom->codigo_1;
		      $registrosArray[$linha]['codigo_2'] = $cupom->codigo_2;
		      $registrosArray[$linha]['codigo_3'] = $cupom->codigo_3;
					$linha++;
				}
			}
    }

    \Excel::create($filename, function($excel) use($registrosArray) {
	    $excel->sheet('Relatório de Cadastros', function($sheet) use ($registrosArray) {
	      $sheet->fromArray($registrosArray);
	    });
		})->download('xls');
  }

}

laravel/app/Http/Controllers/Painel/Receitas/ReceitasController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Receitas;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;
use ItaliaGastronomica\Libs\Thumbs;

use ItaliaGastronomica\Models\Receita;

class ReceitasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Receita::ordenado()->get();

      return view('painel.receitas.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.receitas.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'titulo' => 'required|unique:receitas,titulo',
        'imagem' => 'required|image'
    	]);

      $object = new Receita;

      $object->titulo = $request->titulo;
      $object->slug = str_slug($request->titulo);
      $object->ingredientes = $request->ingredientes;
      $object->preparo = $request->preparo;
      $object->tempo_preparo = $request->tempo_preparo;
      $object->rendimento = $request->rendimento;

      $imagem = Thumbs::make($request, 'imagem', 600, null, 'receitas/');
      if($imagem){
        $object->thumb = $imagem;
        Thumbs::makeFromFile('assets/img/receitas/', $imagem, 200, 200, 'assets/img/receitas/thumbs/');
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.receitas.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.receitas.edit')->with('registro', Receita::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'titulo' => 'required|unique:receitas,titulo,'.$id,
        'imagem' => 'sometimes|image'
    	]);

      $object = Receita::find($id);

      $object->titulo = $request->titulo;
      $object->slug = str_slug($request->titulo);
      $object->ingredientes = $request->ingredientes;
      $object->preparo = $request->preparo;
      $object->tempo_preparo = $request->tempo_preparo;
      $object->rendimento = $request->rendimento;

      $imagem = Thumbs::make($request, 'imagem', 200, 200, 'receitas/');
      if($imagem){
        $object->thumb = $imagem;
        Thumbs::makeFromFile('assets/img/receitas/', $imagem, 200, 200, 'assets/img/receitas/thumbs/');
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.receitas.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Receita::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.receitas.index');
    }

}

laravel/app/Http/Controllers/Painel/Usuarios/UsuariosController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Painel\Usuarios;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;
use View;
use Hash;

use ItaliaGastronomica\Models\User;

class UsuariosController extends Controller{

	public function index()
	{
		$usuarios = User::all();

		return view('painel.usuarios.index')->with(compact('usuarios'));
	}

	public function create()
	{
		return view('painel.usuarios.create');
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'nome' => 'required',
    	'login'             => 'required|unique:users,login',
    	'password'         => 'required|min:6',
    	'password_confirm' => 'required|min:6|same:password',
  	]);

		$object = new User;

		$object->nome = $request->nome;
		$object->login     = $request->login;
		$object->email    = $request->email;
		$object->password = Hash::make($request->password);

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Usuário criado com sucesso.');

			return redirect()->route('painel.usuarios.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar usuário! ('.$e->getMessage().')'));

		}
	}

	public function edit($id)
	{
		$usuario = User::find($id);

		return view('painel.usuarios.edit')->with(compact('usuario'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'nome' => 'required',
    	'login'             => 'required|unique:users,login,'.$id,
    	'password'         => 'min:6',
    	'password_confirm' => 'required_with:password|min:6|same:password',
  	]);

		$object = User::find($id);

		$object->nome = $request->nome;
		$object->email = $request->email;
		$object->login = $request->login;

		if($request->has('password'))
			$object->password = Hash::make($request->password);

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Usuário alterado com sucesso.');

			return redirect()->route('painel.usuarios.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar usuário! ('.$e->getMessage().')'));

		}
	}

	public function destroy(Request $request, $id)
	{
		$object = User::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Usuário removido com sucesso.');

		return redirect()->route('painel.usuarios.index');
	}
}

laravel/app/Http/Controllers/Site/Receitas/ReceitasController.php
<?php

namespace ItaliaGastronomica\Http\Controllers\Site\Receitas;

use Illuminate\Http\Request;
use ItaliaGastronomica\Http\Controllers\Controller;

use ItaliaGastronomica\Models\Receita;

class ReceitasController extends Controller
{

  public function getIndex()
  {
    $receitas = Receita::ordenado()->get();
    return view('site.receitas.index', compact('receitas'));
  }

  public function getDetalhes($slug)
  {
    $receita = Receita::findBySlug($slug);
    return view('site.receitas.detalhes', compact('receita'));
  }

}

laravel/resources/views/painel/receitas/create.blade.php
@extends('painel.template')

@section('conteudo')

    <div class="container-fluid padded-bottom">

    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

	      	<h2>Cadastrar Receita</h2>

	        <hr>

	        @include('painel.partials.mensagens')

		    </div>
		  </div>

      <form action="{{ URL::route('painel.receitas.store') }}" method="post" enctype="multipart/form-data">

  			<input type="hidden" name="_token" value="{!! csrf_token() !!}">

  			<div class="row">
  				<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

            <div class="form-group">
  						<label for="inputTitulo">Título</label>
  						<input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{old('titulo')}}">
  					</div>

            <div class="form-group">
              @if(old('imagem'))
                Thumb atual<br>
                <img src="assets/img/receitas/{{old('imagem')}}"><br>
              @endif
              <label for="inputThumb">Thumb</label>
              <input type="file" class="form-control" id="inputFoto" required name="imagem">
            </div>

            <div class="form-group">
  						<label for="inputIngredientes">Ingredientes</label>
  						<textarea name="ingredientes" id="inputIngredientes" class="form-control">{{old('ingredientes')}}</textarea>
  					</div>

            <div class="form-group">
  						<label for="inputModoPreparo">Modo de Preparo</label>
  						<textarea name="preparo" id="inputModoPreparo" class="form-control">{{old('preparo')}}</textarea>
  					</div>

            <div class="form-group">
  						<label for="inputTPPreparo">Tempo de Preparo</label>
  						<input type="text" name="tempo_preparo" class="form-control" id="inputTPPreparo" value="{{old('tempo_preparo')}}">
  					</div>

            <div class="form-group">
  						<label for="inputRendimento">Rendimento</label>
  						<input type="text" name="rendimento" class="form-control" id="inputRendimento" value="{{old('rendimento')}}">
  					</div>

            <hr>

  				</div>
  			</div>

			  <button type="submit" title="Cadastrar" class="btn btn-success">Cadastrar</button>

			  <a href="{{ URL::route('painel.receitas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	  	</form>

    </div>

@endsection

laravel/resources/views/painel/receitas/edit.blade.php
@extends('painel.template')

@section('conteudo')

    <div class="container-fluid padded-bottom">

    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

	      	<h2>Editar Receita</h2>

	        <hr>

	        @include('painel.partials.mensagens')

		    </div>
		  </div>

      <form action="{{ URL::route('painel.receitas.update', $registro->id) }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PUT">
  			<input type="hidden" name="_token" value="{!! csrf_token() !!}">

  			<div class="row">
  				<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

            <div class="form-group">
  						<label for="inputTitulo">Título</label>
  						<input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{$registro->titulo}}">
  					</div>

            <div class="form-group">
              @if($registro->thumb)
                Thumb atual<br>
                <img src="assets/img/receitas/thumbs/{{$registro->thumb}}"><br>
              @endif
              <label for="inputThumb">Thumb</label>
              <input type="file" class="form-control" id="inputFoto" name="imagem">
            </div>

            <div class="form-group">
  						<label for="inputIngredientes">Ingredientes</label>
  						<textarea name="ingredientes" id="inputIngredientes" class="form-control">{{$registro->ingredientes}}</textarea>
  					</div>

            <div class="form-group">
  						<label for="inputModoPreparo">Modo de Preparo</label>
  						<textarea name="preparo" id="inputModoPreparo" class="form-control">{{$registro->preparo}}</textarea>
  					</div>

            <div class="form-group">
  						<label for="inputTPPreparo">Tempo de Preparo</label>
  						<input type="text" name="tempo_preparo" class="form-control" id="inputTPPreparo" value="{{$registro->tempo_preparo}}">
  					</div>

            <div class="form-group">
  						<label for="inputRendimento">Rendimento</label>
  						<input type="text" name="rendimento" class="form-control" id="inputRendimento" value="{{$registro->rendimento}}">
  					</div>

            <hr>

  				</div>
  			</div>

			  <button type="submit" title="Cadastrar" class="btn btn-success">Cadastrar</button>

			  <a href="{{ URL::route('painel.receitas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	  	</form>

    </div>

@endsection

laravel/resources/views/painel/receitas/index.blade.php
@extends('painel.template')

@section('conteudo')

<div class="container-fluid padded-bottom">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <h2>Receitas</h2>

      @include('painel.partials.mensagens')

      <hr>

      <a href="{{ URL::route('painel.receitas.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Receita</a>

      <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="receitas">

        <thead>
          <tr>
            <th>Ordenad</th>
            <th>Título</th>
            <th><span class="glyphicon glyphicon-cog"></span></th>
          </tr>
        </thead>

        <tbody>
          @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
              <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
              <td>
                {{ $registro->titulo }}
              </td>
              <td class="crud-actions">
                <a href="{{ URL::route('painel.receitas.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

                <form action="{{ URL::route('painel.receitas.destroy', $registro->id) }}" method="post">
                  <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                  <input type="hidden" name="_method" value="DELETE">
                  <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>

      </table>
    </div>
  </div>
</div>

@endsection